#!/usr/bin/env bun
/**
 * Post-process dts-bundle-generator output to wrap in declare module "boltstack".
 */
import { readFileSync, writeFileSync } from "fs";

const file = process.argv[2] || "bolt.d.ts";
const content = readFileSync(file, "utf8");

// Strip generator comment and trailing export {}
const stripped = content
  .replace(/^\/\/ Generated by dts-bundle-generator.*\n\n?/, "")
  .replace(/\nexport \{\};\n?$/, "");

const wrapped = `/**
 * Type declarations for Bolt plugins.
 * Import as: import { PluginBase, handler } from "boltstack";
 */

declare module "boltstack" {
${stripped.split("\n").map(l => l ? "  " + l : "").join("\n").trimEnd()}
}
`;

writeFileSync(file, wrapped, "utf8");
console.log(`Wrapped ${file} in declare module "boltstack"`);
