/**
 * Bundled template for `bolt init`
 * This file is imported directly so it gets included in the bundle.
 */

export const BUNDLED_TEMPLATE = `# Bolt configuration
# Generated by bolt init

project:
  name: \${{ _init.bolt_project_name }}
  engine_repo:
    path: \${{ _init.engine_repo_path }}
    vcs: \${{ _init.engine_repo_vcs }}
    url: \${{ _init.engine_repo_url }}
    branch: \${{ _init.engine_repo_branch }}
  project_repo:
    path: \${{ _init.project_repo_path }}
    vcs: \${{ _init.project_repo_vcs }}
    url: \${{ _init.project_repo_url }}
  uproject: \${{ _init.uproject }}

targets:
  editor:
    kind: editor
    config: development

vars: {}

actions: {}

ops: {}

go-pipeline:
  order: []
  fail_stops: []

plugins: []

_init:
  bolt_project_name:
    prompt: "Bolt project name"
    default: "my-project"

  engine_repo_path:
    prompt: "Engine root path"
    default: "./engine"

  engine_repo_vcs:
    prompt: "Engine VCS"
    type: select
    options: [git, svn]
    default: git

  engine_repo_url:
    prompt: "Engine repo URL"
    required: false

  engine_repo_branch:
    prompt: "Engine branch"
    default: main
    condition: "engine_repo_vcs == 'git'"

  project_repo_path:
    prompt: "Project root path"
    default: "./project"

  project_repo_vcs:
    prompt: "Project VCS"
    type: select
    options: [git, svn]
    default: svn

  project_repo_url:
    prompt: "Project repo URL"
    required: false

  uproject:
    prompt: ".uproject file path"
    required: true
`;
