/**
 * Bundled template for `bolt init`
 * This file is imported directly so it gets included in the bundle.
 */

export const BUNDLED_TEMPLATE = `# Bolt configuration
# Generated by bolt init

project:
  name: \${{ _init.bolt_project_name }}
  engine_repo:
    path: \${{ _init.engine_repo_path }}
    vcs: \${{ _init.engine_repo_vcs }}
    url: \${{ _init.engine_repo_url }}
    branch: \${{ _init.engine_repo_branch }}
  project_repo:
    path: \${{ _init.project_repo_path }}
    vcs: \${{ _init.project_repo_vcs }}
    url: \${{ _init.project_repo_url }}
  uproject: \${{ _init.uproject }}

targets:
  editor:
    kind: editor
    config: development


# Op definitions for \`bolt go\`
# Each op has named variants; "default" is used when no value is given.
ops:
  kill:
    default:
      - uses: ue/kill

  update:
    default:
      - uses: ue/update-git
      - uses: ue/update-svn
    git:
      - uses: ue/update-git
    svn:
      - uses: ue/update-svn

  svn-cleanup:
    default:
      - uses: ue/svn-cleanup

  genproj:
    default:
      - uses: ue/generate-project

  build:
    default:
      - uses: ue/build
        with:
          target: editor
    # Use --build=<target-key> to override the target at runtime
    engine:
      - uses: ue/build-engine
        with:
          config: development
    editor:
      - uses: ue/build
        with:
          target: editor
    program:
      - uses: ue/build
        with:
          target: program
          # Supply target at runtime:
          #   bolt go build:program --target=UnrealInsights

  start:
    default:
      - uses: ue/start

  info:
    default:
      - uses: ue/info

  fix-dll:
    default:
      - uses: ue/fix-dll

# go-pipeline controls bolt go execution order and failure behaviour
go-pipeline:
  order:
    - kill
    - info
    - update
    - svn-cleanup
    - genproj
    - build
    - fillddc
    - fix-dll
    - start
  fail_stops:
    - build # if build fails, stop; other ops continue on failure

# Named action profiles (reusable, runnable with \`bolt run <name>\`)
actions:
  build_editor:
    steps:
      - uses: ue/build
        with:
          target: editor
          config: development

  build_editor_with_ops:
    steps:
      - uses: ops/build
        with:
          config: debug

  build_editor_steps:
    steps:
      - uses: ue/build-engine
        with:
          config: development
      - uses: ue/build-editor
        with:
          config: debug

  build_and_start_editor:
    steps:
      - uses: ue/build
        with:
          target: editor
      - uses: ue/start

  daily_check:
    steps:
      - uses: ops/update:svn
      - uses: ops/build
      - uses: ops/start
        continue-on-error: true

  full_reset:
    steps:
      - uses: ops/kill
        continue-on-error: true
      - uses: ops/update
      - uses: ops/genproj
      - uses: ops/build

_init:
  bolt_project_name:
    prompt: "Bolt project name"
    default: "my-project"

  engine_repo_path:
    prompt: "Engine root path"
    default: "./engine"

  engine_repo_vcs:
    prompt: "Engine VCS"
    type: select
    options:
      - "git"
      - "svn"
    default: "git"

  engine_repo_url:
    prompt: "Engine repo URL"
    required: false

  engine_repo_branch:
    prompt: "Engine branch"
    default: "main"
    condition: "engine_repo_vcs == 'git'"

  project_repo_path:
    prompt: "Project root path"
    default: "./project"

  project_repo_vcs:
    prompt: "Project VCS"
    type: select
    options:
      - "git"
      - "svn"
    default: "svn"

  project_repo_url:
    prompt: "Project repo URL"
    required: false

  uproject:
    prompt: ".uproject file path"
    required: true
`;
