import { existsSync, mkdirSync, writeFileSync } from "fs";
import path from "path";
import { YAML } from "bun";
import type { InitAnswers } from "./questions";

export interface GenerateOptions extends InitAnswers {
  location: string;
}

export interface GenerateResult {
  ok: true;
  path: string;
}

export interface GenerateError {
  ok: false;
  error: string;
}

export type GeneratorResult = GenerateResult | GenerateError;

/**
 * Extract project name from .uproject file path
 */
function getProjectName(uprojectPath: string): string {
  const basename = path.basename(uprojectPath);
  return basename.replace(/\.uproject$/i, "");
}

/**
 * Generate bolt.yaml from answers.
 */
export function generateConfig(
  answers: GenerateOptions,
  template?: string
): GeneratorResult {
  const targetDir = path.isAbsolute(answers.location)
    ? answers.location
    : path.join(process.cwd(), answers.location);

  // Create directory if it doesn't exist
  if (!existsSync(targetDir)) {
    try {
      mkdirSync(targetDir, { recursive: true });
    } catch (err) {
      return { ok: false, error: `Failed to create directory: ${err}` };
    }
  }

  const configPath = path.join(targetDir, "bolt.yaml");

  // Check if bolt.yaml already exists
  if (existsSync(configPath)) {
    return { ok: false, error: `bolt.yaml already exists at ${configPath}` };
  }

  let content: string;

  if (template) {
    content = substituteTemplate(template, answers);
  } else {
    content = generateFromAnswers(answers);
  }

  try {
    writeFileSync(configPath, content, "utf8");
    return { ok: true, path: configPath };
  } catch (err) {
    return { ok: false, error: `Failed to write config: ${err}` };
  }
}

function substituteTemplate(template: string, answers: GenerateOptions): string {
  const projectName = getProjectName(answers.uproject);
  const replacements: Record<string, string> = {
    BOLT_PROJECT_NAME: answers.bolt_project_name || projectName,
    ENGINE_REPO_PATH: answers.engine_repo_path,
    ENGINE_REPO_VCS: answers.engine_repo_vcs,
    ENGINE_REPO_URL: answers.engine_repo_url || "",
    ENGINE_REPO_BRANCH: answers.engine_repo_branch || "main",
    PROJECT_REPO_PATH: answers.project_repo_path,
    PROJECT_REPO_VCS: answers.project_repo_vcs,
    PROJECT_REPO_URL: answers.project_repo_url || "",
    UPROJECT: answers.uproject,
  };

  let result = template;
  for (const [key, value] of Object.entries(replacements)) {
    result = result.replace(new RegExp(`\\$\\{${key}\\}`, "g"), value);
  }
  return result;
}

function generateFromAnswers(answers: GenerateOptions): string {
  const projectName = getProjectName(answers.uproject);

  const engineRepo: Record<string, unknown> = {
    path: answers.engine_repo_path || "./engine",
    vcs: answers.engine_repo_vcs || "git",
  };
  if (answers.engine_repo_url) engineRepo.url = answers.engine_repo_url;
  if (answers.engine_repo_branch) engineRepo.branch = answers.engine_repo_branch;

  const projectRepo: Record<string, unknown> = {
    path: answers.project_repo_path || "./project",
    vcs: answers.project_repo_vcs || "svn",
  };
  if (answers.project_repo_url) projectRepo.url = answers.project_repo_url;

  const config: Record<string, unknown> = {
    project: {
      name: answers.bolt_project_name || projectName,
      engine_repo: engineRepo,
      project_repo: projectRepo,
      uproject: answers.uproject,
    },
    vars: {},
    targets: {},
    actions: {},
    ops: {},
    "go-pipeline": {
      order: [],
      fail_stops: [],
    },
    plugins: [],
  };

  // Add targets based on selection
  const targetConfigs: Record<string, Record<string, unknown>> = {
    editor: { kind: "editor", config: "development" },
    client: { kind: "program", name: `${projectName}Client`, config: "shipping" },
    server: { kind: "program", name: `${projectName}Server`, config: "shipping" },
  };

  for (const target of answers.targets || ["editor"]) {
    if (targetConfigs[target]) {
      config.targets[target] = targetConfigs[target];
    }
  }

  // Add notifications if enabled
  if (answers.notifications && answers.webhook_url) {
    config.notifications = {
      on_success: true,
      on_failure: true,
      webhook_url: answers.webhook_url,
    };
  }

  return `# Bolt configuration\n# Generated by bolt init\n\n${YAML.stringify(config, null, 2)}`;
}
