import { existsSync, readFileSync } from "fs";
import path from "path";

export interface TemplateResult {
  ok: true;
  content: string;
  source: string;
}

export interface TemplateError {
  ok: false;
  error: string;
}

export type TemplateLoadResult = TemplateResult | TemplateError;

/**
 * Load template from local file, remote URL, or bundled fallback.
 * Priority: remote > local > cwd template > bundled fallback
 */
export async function loadTemplate(options: {
  remote?: string;
  template?: string;
}): Promise<TemplateLoadResult> {
  const { remote, template } = options;

  // 1. Remote URL
  if (remote) {
    try {
      const res = await fetch(remote);
      if (!res.ok) {
        return { ok: false, error: `Failed to fetch remote: ${res.status} ${res.statusText}` };
      }
      const content = await res.text();
      return { ok: true, content, source: remote };
    } catch (err) {
      return { ok: false, error: `Failed to fetch remote: ${err}` };
    }
  }

  // 2. Local template path
  if (template) {
    const templatePath = path.resolve(template);
    if (!existsSync(templatePath)) {
      return { ok: false, error: `Template file not found: ${templatePath}` };
    }
    try {
      const content = readFileSync(templatePath, "utf8");
      return { ok: true, content, source: templatePath };
    } catch (err) {
      return { ok: false, error: `Failed to read template: ${err}` };
    }
  }

  // 3. bolt.template.yaml in cwd
  const cwdTemplate = path.join(process.cwd(), "bolt.template.yaml");
  if (existsSync(cwdTemplate)) {
    try {
      const content = readFileSync(cwdTemplate, "utf8");
      return { ok: true, content, source: cwdTemplate };
    } catch {
      // Fall through to bundled
    }
  }

  // 4. Bundled fallback (minimal template)
  const bundledTemplate = getBundledTemplate();
  return { ok: true, content: bundledTemplate, source: "bundled" };
}

function getBundledTemplate(): string {
  return `# Bolt configuration
# Generated by bolt init

project:
  name: \${PROJECT_NAME}
  engine_root: \${ENGINE_ROOT}
  project_root: \${PROJECT_ROOT}
  project_name: \${UPROJECT_NAME}
  git_branch: \${GIT_BRANCH}

vars: {}

targets:
  editor:
    kind: editor
    config: development

actions: {}

ops: {}

go-pipeline:
  order: []
  fail_stops: []

plugins: []
`;
}
