import { createHash } from "crypto";
import { readFileSync } from "fs";
import type { BoltConfig } from "./config";
import type { PluginRegistry } from "./plugin-registry";
import { getParamMap } from "./plugin";
import { resolveRunPlan, type PlanNode } from "./run-plan";

/** Describe a resolved plugin/local action using the plugin's describe() if available. */
function describeUses(
  ref: string,
  params: Record<string, string>,
  registry: PluginRegistry,
): string {
  // Plugin call: "namespace/handler"
  const slash = ref.indexOf("/");
  if (slash === -1) return ref;

  const ns = ref.slice(0, slash);
  const handler = ref.slice(slash + 1);
  const plugin = registry.get(ns);
  if (!plugin) return ref;

  if (plugin.describe) {
    const desc = plugin.describe(handler, params);
    if (desc) return desc;
  }

  const paramMap = getParamMap(plugin as any, handler);
  if (paramMap && paramMap.size > 0) {
    const paramDescs = [...paramMap.entries()].map(
      ([name, meta]) => `${name}: ${meta.description}`,
    );
    return `${ref} (${paramDescs.join(", ")})`;
  }

  return ref;
}

function describePlanNodes(nodes: PlanNode[], registry: PluginRegistry): string {
  return nodes
    .map((node) => {
      if (node.kind === "run") return node.command;
      if (node.kind === "uses") return describeUses(node.ref, node.params, registry);
      return describePlanNodes(node.nodes, registry) || `call:${node.name}`;
    })
    .join(" → ");
}

function describeInvalidPlan(messages: string[]): string {
  for (const message of messages) {
    if (message.startsWith("Task call cycle: ")) {
      const name = message.slice("Task call cycle: ".length).split(" -> ").at(-1);
      return `call:${name ?? "?"} (cycle)`;
    }
    const unknown = message.match(/^Unknown task: "(.+)"$/);
    if (unknown) return `call:${unknown[1]}`;
  }
  return messages.join("; ");
}

/** Describe a task from the same effective plan used for execution and inspection. */
function describeTask(
  name: string,
  cfg: BoltConfig,
  registry: PluginRegistry,
  params: Record<string, string>,
): string {
  const result = resolveRunPlan(cfg, { kind: "tasks", names: [name], params });
  if (!result.ok) return describeInvalidPlan(result.errors.map((error) => error.message));
  return describePlanNodes(result.plan.tasks[0]?.nodes ?? [], registry);
}

export function generateAiContext(
  cfg: BoltConfig,
  configPath: string,
  registry: PluginRegistry,
  params: Record<string, string> = {},
): string {
  const yamlRaw = readFileSync(configPath, "utf8");
  const hash = createHash("sha256").update(yamlRaw).digest("hex").slice(0, 16);

  const lines: string[] = [];

  lines.push(`<!-- generated by bolt ai — do not edit manually -->`);
  lines.push(`<!-- bolt.yaml hash: ${hash} -->`);
  lines.push(`<!-- config: ${configPath} -->`);
  lines.push(``);
  lines.push(`# Bolt — ${cfg.project.name}`);
  lines.push(``);
  lines.push(`Bolt is a CLI tool for Unreal Engine workflow automation.`);
  lines.push(`Run commands from the directory containing bolt.yaml (or any child directory).`);
  lines.push(``);
  lines.push(`Model: a **task** is a named list of steps; a **flow** is an ordered set of`);
  lines.push(`tasks with a fail policy. \`bolt run <task...>\` runs tasks in the order given;`);
  lines.push(`\`bolt run <flow>\` runs a predefined flow.`);
  lines.push(
    `Step keys: \`uses\`: plugin/local action; \`call\`: reusable task; \`run\`: shell command.`,
  );
  lines.push(``);

  // --- Quick reference table ---
  lines.push(`## Quick Reference`);
  lines.push(``);
  lines.push(`| Name | Command | Steps |`);
  lines.push(`|------|---------|-------|`);

  for (const name of Object.keys(cfg.tasks)) {
    lines.push(`| ${name} | \`bolt run ${name}\` | ${describeTask(name, cfg, registry, params)} |`);
  }
  for (const [name, flow] of Object.entries(cfg.flows)) {
    lines.push(`| ${name} (flow) | \`bolt run ${name}\` | ${flow.steps.join(" → ")} |`);
  }
  lines.push(``);

  // --- Tasks detail ---
  lines.push(`## Tasks (\`bolt run <task...>\`)`);
  lines.push(``);
  lines.push(
    `Named step sequences. Chain multiple in typed order: \`bolt run update build start\`.`,
  );
  lines.push(
    `Pass params with \`--key=value\` (applies to the whole run, e.g. \`--target=client\`).`,
  );
  lines.push(``);

  for (const name of Object.keys(cfg.tasks)) {
    lines.push(
      `- **${name}** — \`bolt run ${name}\` — ${describeTask(name, cfg, registry, params)}`,
    );
  }
  lines.push(``);

  // --- Flows detail ---
  if (Object.keys(cfg.flows).length > 0) {
    lines.push(`## Flows (\`bolt run <flow>\`)`);
    lines.push(``);
    lines.push(`Ordered task compositions. Fail-fast: the first failing task aborts the flow,`);
    lines.push(`unless it is listed in \`continue_on_fail\`.`);
    lines.push(``);

    for (const [name, flow] of Object.entries(cfg.flows)) {
      const cont = flow.continue_on_fail.length
        ? ` (continue_on_fail: ${flow.continue_on_fail.join(", ")})`
        : "";
      const desc = flow.description ? `${flow.description} — ` : "";
      lines.push(`- **${name}**${cont}: ${desc}${flow.steps.join(" → ")}`);
    }
    lines.push(``);
  }

  // --- Targets ---
  if (Object.keys(cfg.targets).length > 0) {
    lines.push(`## Targets`);
    lines.push(``);
    for (const [name, t] of Object.entries(cfg.targets)) {
      const detail = t.name ? `${t.kind} · ${t.name} · ${t.config}` : `${t.kind} · ${t.config}`;
      lines.push(`- **${name}**: ${detail}`);
    }
    lines.push(``);
  }

  // --- Flags ---
  lines.push(`## Flags`);
  lines.push(``);
  lines.push(`- \`--dry-run\` — preview steps without executing`);
  lines.push(
    `- \`--key=value\` — pass parameters to the run (e.g. \`--target=client --config=debug\`)`,
  );
  lines.push(`- \`--config=debuggame\` (aliases: \`dbggame\`, \`DebugGame\`) — Unreal DebugGame`);
  lines.push(``);

  lines.push(`## Notifications`);
  lines.push(``);
  lines.push(
    `Start notifications show the top-level task list and recursively owned actions once per invocation.`,
  );
  lines.push(``);

  // --- Introspection ---
  lines.push(`## Introspection`);
  lines.push(``);
  lines.push(`- \`bolt list\` — list all tasks and flows`);
  lines.push(`- \`bolt inspect <name...>\` — show resolved steps for a task or flow`);
  lines.push(`- \`bolt info\` — project and VCS summary`);
  lines.push(`- \`bolt check\` — validate bolt.yaml schema`);
  lines.push(``);

  return lines.join("\n");
}
