import { createHash } from "crypto";
import { readFileSync } from "fs";
import type { BoltConfig, Step } from "./config";
import { getOpVariant, getOpVariants } from "./config";
import type { PluginRegistry } from "./plugin-registry";
import { getParamMap } from "./plugin";

/** Describe a single step using the plugin's describe() if available. */
function describeStep(step: Step, registry: PluginRegistry): string {
  if (step.run) return step.run;
  if (!step.uses) return "?";

  // Resolve ops/ references — just show as "ops/<name>"
  if (step.uses.startsWith("ops/")) return step.uses;

  // Plugin call: "namespace/handler"
  const slash = step.uses.indexOf("/");
  if (slash === -1) return step.uses;

  const ns = step.uses.slice(0, slash);
  const handler = step.uses.slice(slash + 1);
  const plugin = registry.get(ns);
  if (!plugin) return step.uses;

  // Try describe() first (existing behavior)
  if (plugin.describe) {
    const params = step.with ?? {};
    const desc = plugin.describe(handler, params);
    if (desc) return desc;
  }

  // Fallback: use @param metadata to show parameter info
  const paramMap = getParamMap(plugin as any, handler);
  if (paramMap && paramMap.size > 0) {
    const paramDescs = [...paramMap.entries()].map(([name, meta]) => `${name}: ${meta.description}`);
    return `${step.uses} (${paramDescs.join(", ")})`;
  }

  return step.uses;
}

/** Describe an op variant by describing its steps. */
function describeVariant(
  opName: string,
  variant: string,
  cfg: BoltConfig,
  registry: PluginRegistry,
): string {
  const steps = getOpVariant(cfg.ops[opName], variant);
  if (!steps || steps.length === 0) return "";
  return steps.map((s) => describeStep(s, registry)).join(" → ");
}

/** Describe an action by describing its steps (resolving ops/ inline). */
function describeAction(
  steps: Step[],
  cfg: BoltConfig,
  registry: PluginRegistry,
): string {
  return steps.map((step) => {
    if (step.uses?.startsWith("ops/")) {
      const rest = step.uses.slice("ops/".length);
      const [opName, variant = "default"] = rest.split(":");
      const opSteps = getOpVariant(cfg.ops[opName] ?? {}, variant);
      if (opSteps) {
        return opSteps.map((s) => describeStep(s, registry)).join(" → ");
      }
    }
    return describeStep(step, registry);
  }).join(" → ");
}

export function generateAiContext(
  cfg: BoltConfig,
  configPath: string,
  registry: PluginRegistry,
): string {
  const yamlRaw = readFileSync(configPath, "utf8");
  const hash = createHash("sha256").update(yamlRaw).digest("hex").slice(0, 16);

  const lines: string[] = [];

  lines.push(`<!-- generated by bolt ai — do not edit manually -->`);
  lines.push(`<!-- bolt.yaml hash: ${hash} -->`);
  lines.push(`<!-- config: ${configPath} -->`);
  lines.push(``);
  lines.push(`# Bolt — ${cfg.project.name}`);
  lines.push(``);
  lines.push(`Bolt is a CLI tool for Unreal Engine workflow automation.`);
  lines.push(`Run commands from the directory containing bolt.yaml (or any child directory).`);
  lines.push(``);

  // --- Quick reference table ---
  lines.push(`## Quick Reference`);
  lines.push(``);
  lines.push(`| Task | Command | Description |`);
  lines.push(`|------|---------|-------------|`);

  for (const [opName, op] of Object.entries(cfg.ops)) {
    const variants = getOpVariants(op);
    for (const v of variants) {
      const label = v === "default" ? opName : `${opName}:${v}`;
      const cmd = v === "default" ? `bolt go ${opName}` : `bolt go ${opName}:${v}`;
      const desc = describeVariant(opName, v, cfg, registry);
      lines.push(`| ${label} | \`${cmd}\` | ${desc} |`);
    }
  }

  for (const [actionName, action] of Object.entries(cfg.actions)) {
    const desc = describeAction(action.steps, cfg, registry);
    lines.push(`| ${actionName} | \`bolt run ${actionName}\` | ${desc} |`);
  }

  lines.push(``);

  // --- Ops detail ---
  lines.push(`## Ops (\`bolt go <op>[:<variant>]\`)`);
  lines.push(``);
  lines.push(`Pipeline ops. Can chain multiple: \`bolt go update build start\`.`);
  lines.push(`Pipeline order: ${cfg["go-pipeline"].order.join(" → ") || "(none)"}`);
  if (cfg["go-pipeline"].fail_stops.length > 0) {
    lines.push(`Fail stops: ${cfg["go-pipeline"].fail_stops.join(", ")}`);
  }
  lines.push(``);

  for (const [opName, op] of Object.entries(cfg.ops)) {
    const variants = getOpVariants(op);
    for (const v of variants) {
      const cmd = v === "default" ? `\`bolt go ${opName}\`` : `\`bolt go ${opName}:${v}\``;
      const label = v === "default" ? `**${opName}**` : `**${opName}:${v}**`;
      const desc = describeVariant(opName, v, cfg, registry);
      lines.push(`- ${label} — ${cmd} — ${desc}`);
    }
  }
  lines.push(``);

  // --- Actions detail ---
  if (Object.keys(cfg.actions).length > 0) {
    lines.push(`## Actions (\`bolt run <action>\`)`);
    lines.push(``);
    lines.push(`Standalone workflows, independent of pipeline order.`);
    lines.push(``);

    for (const [name, action] of Object.entries(cfg.actions)) {
      const deps = action.depends?.length ? ` (depends: ${action.depends.join(", ")})` : "";
      const desc = describeAction(action.steps, cfg, registry);
      lines.push(`- **${name}**${deps}: ${desc}`);
    }
    lines.push(``);
  }

  // --- Targets ---
  if (Object.keys(cfg.targets).length > 0) {
    lines.push(`## Targets`);
    lines.push(``);
    for (const [name, t] of Object.entries(cfg.targets)) {
      const detail = t.name ? `${t.kind} · ${t.name} · ${t.config}` : `${t.kind} · ${t.config}`;
      lines.push(`- **${name}**: ${detail}`);
    }
    lines.push(``);
  }

  // --- Flags ---
  lines.push(`## Flags`);
  lines.push(``);
  lines.push(`- \`--dry-run\` — preview steps without executing`);
  lines.push(`- \`--key=value\` — pass parameters to ops/actions (e.g. \`--target=UnrealInsights\`)`);
  lines.push(``);

  // --- Introspection ---
  lines.push(`## Introspection`);
  lines.push(``);
  lines.push(`- \`bolt list\` — list all ops and actions`);
  lines.push(`- \`bolt inspect go <op>\` — show resolved steps for an op`);
  lines.push(`- \`bolt inspect run <action>\` — show resolved steps for an action`);
  lines.push(`- \`bolt info\` — project and VCS summary`);
  lines.push(`- \`bolt check\` — validate bolt.yaml schema`);
  lines.push(``);

  return lines.join("\n");
}
