import { createHash } from "crypto";
import { readFileSync } from "fs";
import type { BoltConfig } from "./config";
import { getOpVariants, getOpDescription } from "./config";

export function generateAiContext(cfg: BoltConfig, configPath: string): string {
  const yamlRaw = readFileSync(configPath, "utf8");
  const hash = createHash("sha256").update(yamlRaw).digest("hex").slice(0, 16);

  const lines: string[] = [];

  lines.push(`<!-- generated by bolt ai — do not edit manually -->`);
  lines.push(`<!-- bolt.yaml hash: ${hash} -->`);
  lines.push(`<!-- config: ${configPath} -->`);
  lines.push(``);
  lines.push(`# Bolt — ${cfg.project.name}`);
  lines.push(``);
  lines.push(`Bolt is a CLI tool for Unreal Engine workflow automation.`);
  lines.push(`Run commands from the directory containing bolt.yaml (or any child directory).`);
  lines.push(``);

  // --- Quick reference table ---
  lines.push(`## Quick Reference`);
  lines.push(``);
  lines.push(`| Task | Command | Description |`);
  lines.push(`|------|---------|-------------|`);

  // Ops
  for (const [opName, op] of Object.entries(cfg.ops)) {
    const desc = getOpDescription(op) ?? "";
    const variants = getOpVariants(op);
    if (variants.length === 1 && variants[0] === "default") {
      lines.push(`| ${opName} | \`bolt go ${opName}\` | ${desc} |`);
    } else {
      for (const v of variants) {
        const label = v === "default" ? opName : `${opName} (${v})`;
        const cmd = v === "default" ? `bolt go ${opName}` : `bolt go ${opName}:${v}`;
        lines.push(`| ${label} | \`${cmd}\` | ${desc} |`);
      }
    }
  }

  // Actions
  for (const [actionName, action] of Object.entries(cfg.actions)) {
    const desc = action.description ?? "";
    lines.push(`| ${actionName} | \`bolt run ${actionName}\` | ${desc} |`);
  }

  lines.push(``);

  // --- Ops detail ---
  lines.push(`## Ops (\`bolt go <op>[:<variant>]\`)`);
  lines.push(``);
  lines.push(`Pipeline ops. Can chain multiple: \`bolt go update build start\`.`);
  lines.push(`Pipeline order: ${cfg["go-pipeline"].order.join(" → ") || "(none)"}`);
  if (cfg["go-pipeline"].fail_stops.length > 0) {
    lines.push(`Fail stops: ${cfg["go-pipeline"].fail_stops.join(", ")}`);
  }
  lines.push(``);

  for (const [opName, op] of Object.entries(cfg.ops)) {
    const desc = getOpDescription(op);
    const variants = getOpVariants(op);
    if (variants.length === 1 && variants[0] === "default") {
      lines.push(`- **${opName}** — \`bolt go ${opName}\`${desc ? ` — ${desc}` : ""}`);
    } else {
      const variantList = variants
        .map((v) => (v === "default" ? `\`bolt go ${opName}\`` : `\`bolt go ${opName}:${v}\``))
        .join(", ");
      lines.push(`- **${opName}** — ${variantList}${desc ? ` — ${desc}` : ""}`);
    }
  }
  lines.push(``);

  // --- Actions detail ---
  if (Object.keys(cfg.actions).length > 0) {
    lines.push(`## Actions (\`bolt run <action>\`)`);
    lines.push(``);
    lines.push(`Standalone workflows, independent of pipeline order.`);
    lines.push(``);

    for (const [name, action] of Object.entries(cfg.actions)) {
      const desc = action.description;
      const deps = action.depends?.length ? ` (depends: ${action.depends.join(", ")})` : "";
      if (desc) {
        lines.push(`- **${name}**${deps}: ${desc}`);
      } else {
        const stepSummary = action.steps
          .map((s) => s.uses ?? s.run ?? "?")
          .join(" → ");
        lines.push(`- **${name}**${deps}: ${stepSummary}`);
      }
    }
    lines.push(``);
  }

  // --- Targets ---
  if (Object.keys(cfg.targets).length > 0) {
    lines.push(`## Targets`);
    lines.push(``);
    for (const [name, t] of Object.entries(cfg.targets)) {
      const detail = t.name ? `${t.kind} · ${t.name} · ${t.config}` : `${t.kind} · ${t.config}`;
      lines.push(`- **${name}**: ${detail}`);
    }
    lines.push(``);
  }

  // --- Flags ---
  lines.push(`## Flags`);
  lines.push(``);
  lines.push(`- \`--dry-run\` — preview steps without executing`);
  lines.push(`- \`--key=value\` — pass parameters to ops/actions (e.g. \`--target=UnrealInsights\`)`);
  lines.push(``);

  // --- Introspection ---
  lines.push(`## Introspection`);
  lines.push(``);
  lines.push(`- \`bolt list\` — list all ops and actions`);
  lines.push(`- \`bolt inspect go <op>\` — show resolved steps for an op`);
  lines.push(`- \`bolt inspect run <action>\` — show resolved steps for an action`);
  lines.push(`- \`bolt info\` — project and VCS summary`);
  lines.push(`- \`bolt check\` — validate bolt.yaml schema`);
  lines.push(``);

  return lines.join("\n");
}
